auto: true

markdown: rdiscount
#highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Thunder Troop's Blog
url: http://thunder-troop.github.io
description: Workspace of Thunder Troop
feed: /atom.xml
author_info: <a href="http://thunder-troop.github.io/">Thunder Troop</a>
